version: "3"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'department'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'hr'
    networks:
      - app

  rest-server:
    image: tomcat:9-jre8
    container_name: rest-server
    volumes:
      - ./rest/target/rest.war:/usr/local/tomcat/webapps/rest.war
      - /tmp/logs/rest-logs:/usr/local/tomcat/logs
    environment:
      - DRIVER_DB=org.postgresql.Driver
      - HOST_DB=jdbc:postgresql://postgres:5432/department?stringtype=unspecified
      - USER_NAME=hr
      - PASSWORD_DB=postgres
      - DATABASE=postgres
    links:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - app
  rest-client:
    image: tomcat:9-jre8
    container_name: rest-client
    environment:
      - "JAVA_OPTS=-Dprofile=docker"
    volumes:
      - ./webapp/target/webapp.war:/usr/local/tomcat/webapps/webapp.war
      - /tmp/logs/webapp_logs:/usr/local/tomcat/logs
    ports:
      - "8082:8080"
    depends_on:
      - "rest-server"
    networks:
      - app

networks:
  app:
    driver: bridge