version: "3"

services:
  rest-server:
    image: rest_server:latest
    container_name: rest-server
    ports:
      - "8081:8080"
  rest-client:
    image: rest_client:latest
    container_name: rest-client
    ports:
      - "8082:8080"
    depends_on:
      - "rest-server"