version: "2.1"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'department'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'hr'
    networks:
      - "app"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    ports:
      - "9411:9411"
    depends_on:
      - "elasticsearch"
    networks:
      - "app"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - "app"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.7.0
    container_name: logstash
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - "app"
    depends_on:
      - "elasticsearch"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.7.0
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - "app"
    depends_on:
      - "elasticsearch"
      - "logstash"
      
  rest-server:
    image: openjdk:8
    container_name: rest-server
    volumes:
      - ./rest/target/rest.jar:/usr/src/rest.jar
      - /tmp/logs/rest-logs:/usr/local/tomcat/logs
    links:
      - "postgres"
    command: bash -c "cd /usr/src/ && java -jar rest.jar"
    stdin_open: false
    tty: true
    ports:
      - "8081:8080"
    depends_on:
      - "zipkin"
      - "logstash"
    networks:
      - "app"

  rest-client:
    image: openjdk:8
    container_name: rest-client
    volumes:
      - ./webapp/target/webapp.jar:/usr/src/webapp.jar
      - /tmp/logs/webapp_logs:/usr/local/tomcat/logs
    command: bash -c "cd /usr/src/ && java -jar webapp.jar"
    ports:
      - "8082:8080"
    stdin_open: false
    tty: true
    depends_on:
      - "zipkin"
      - "logstash"
      - "rest-server"
    networks:
      - "app"

networks:
  app:
    driver: bridge