version: "3"

services:
  soap-server:
    image: tomcat:9-jre8
    container_name: soap-server
    volumes:
      - ./soap/target/soap.war:/usr/local/tomcat/webapps/soap.war
      - /tmp/logs/soap_logs:/usr/local/tomcat/logs
    ports:
      - "8083:8080"
  rest-client:
    image: tomcat:9-jre8
    container_name: rest-client
    environment:
      - "JAVA_OPTS=-Dprofile=docker"
    volumes:
      - ./webapp/target/webapp.war:/usr/local/tomcat/webapps/webapp.war
      - /tmp/logs/webapp_logs:/usr/local/tomcat/logs
    ports:
      - "8082:8080"