version: "2.1"

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    networks:
      - app

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
    depends_on:
      - storage
    networks:
      - app

  rest-server:
    image: tomcat:9-jre8
    container_name: rest-server
    volumes:
      - ./rest/target/rest.war:/usr/local/tomcat/webapps/rest.war
      - rest-logs:/usr/local/tomcat/logs
    ports:
      - 8081:8080
    depends_on:
      - zipkin
    networks:
      - app

  rest-client:
    image: tomcat:9-jre8
    container_name: rest-client
    environment:
      - "JAVA_OPTS=-Dprofile=docker"
    volumes:
      - ./webapp/target/webapp.war:/usr/local/tomcat/webapps/webapp.war
      - webapp-logs:/usr/local/tomcat/logs
    ports:
      - 8082:8080
    depends_on:
      zipkin:
        condition: service_started
      rest-server:
        condition: service_started
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  webapp-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tmp/logs/webapp_logs
  rest-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tmp/logs/rest_logs
