DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS EMPLOYEES;
-- DROP TABLE IF EXISTS SALARY;

CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
  DEPARTMENT_ID INT PRIMARY KEY NOT NULL IDENTITY,
  DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
  EMPLOYEE_ID INT PRIMARY KEY NOT NULL IDENTITY,
  EMPLOYEE_DEPARTMENT_ID INT NOT NULL,
  EMPLOYEE_FULL_NAME VARCHAR(100) NOT NULL,
  EMPLOYEE_DATE_OF_BIRTHDAY DATETIME NOT NULL,
  EMPLOYEE_SALARY DECIMAL NOT NULL,
  EMPLOYEE_CURRENCY VARCHAR(3) NOT NULL,
  CONSTRAINT EMPLOYEES_DEPARTMENT_ID_FK FOREIGN KEY (EMPLOYEE_DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

-- CREATE TABLE IF NOT EXISTS SALARY
-- (
--   EMPLOYEE_ID INT NOT NULL UNIQUE,
--   SALARY_AMOUNT DECIMAL NOT NULL,
--   SALARY_CURRENCY VARCHAR(10) NOT NULL,
--   CONSTRAINT EMPLOYEE_SALARY_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
-- );
--
