DROP TABLE IF EXISTS "EMPLOYEES";
DROP TABLE IF EXISTS "DEPARTMENTS";

CREATE TABLE IF NOT EXISTS "DEPARTMENTS"
(
  "DEPARTMENT_ID"   BIGSERIAL    NOT NULL PRIMARY KEY,
  "DEPARTMENT_NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "EMPLOYEES"
(
  "EMPLOYEE_ID"               BIGSERIAL          NOT NULL PRIMARY KEY,
  "EMPLOYEE_DEPARTMENT_ID"    BIGINT             NULL,
  "EMPLOYEE_FULL_NAME"        VARCHAR(100)       NULL,
  "EMPLOYEE_DATE_OF_BIRTHDAY" TIMESTAMP          NULL,
  "EMPLOYEE_SALARY"           DECIMAL(34, 2)     NULL,
  CONSTRAINT "EMPLOYEES_DEPARTMENT_ID_FK"
    FOREIGN KEY ("EMPLOYEE_DEPARTMENT_ID")
    REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);