DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;

CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
  DEPARTMENT_ID   BIGINT PRIMARY KEY NOT NULL IDENTITY,
  DEPARTMENT_NAME VARCHAR(100)       NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
  EMPLOYEE_ID               BIGINT PRIMARY KEY NOT NULL IDENTITY,
  EMPLOYEE_DEPARTMENT_ID    BIGINT             NOT NULL,
  EMPLOYEE_FULL_NAME        VARCHAR(100)       NOT NULL,
  EMPLOYEE_DATE_OF_BIRTHDAY DATE               NOT NULL,
  EMPLOYEE_SALARY           DECIMAL (34, 10)    NOT NULL,
  CONSTRAINT EMPLOYEES_DEPARTMENT_ID_FK FOREIGN KEY (EMPLOYEE_DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);