//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.12 at 01:32:09 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.human-resources.com/definition", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nikolay.model.xsds;
