//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.26 at 06:03:53 PM MSK 
//


package com.nikolay.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javaspringclub.gs_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javaspringclub.gs_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDepartmentByIdRequest }
     * 
     */
    public GetDepartmentByIdRequest createGetDepartmentByIdRequest() {
        return new GetDepartmentByIdRequest();
    }

    /**
     * Create an instance of {@link GetDepartmentByIdResponse }
     * 
     */
    public GetDepartmentByIdResponse createGetDepartmentByIdResponse() {
        return new GetDepartmentByIdResponse();
    }

    /**
     * Create an instance of {@link DepartmentDtoResponse }
     * 
     */
    public DepartmentDtoResponse createDepartmentDtoResponse() {
        return new DepartmentDtoResponse();
    }

    /**
     * Create an instance of {@link GetAllDepartmentsRequest }
     * 
     */
    public GetAllDepartmentsRequest createGetAllDepartmentsRequest() {
        return new GetAllDepartmentsRequest();
    }

    /**
     * Create an instance of {@link GetAllDepartmentsResponse }
     * 
     */
    public GetAllDepartmentsResponse createGetAllDepartmentsResponse() {
        return new GetAllDepartmentsResponse();
    }

    /**
     * Create an instance of {@link AddDepartmentRequest }
     * 
     */
    public AddDepartmentRequest createAddDepartmentRequest() {
        return new AddDepartmentRequest();
    }

    /**
     * Create an instance of {@link AddDepartmentResponse }
     * 
     */
    public AddDepartmentResponse createAddDepartmentResponse() {
        return new AddDepartmentResponse();
    }

    /**
     * Create an instance of {@link UpdateDepartmentRequest }
     * 
     */
    public UpdateDepartmentRequest createUpdateDepartmentRequest() {
        return new UpdateDepartmentRequest();
    }

    /**
     * Create an instance of {@link DepartmentResponse }
     * 
     */
    public DepartmentResponse createDepartmentResponse() {
        return new DepartmentResponse();
    }

    /**
     * Create an instance of {@link UpdateDepartmentResponse }
     * 
     */
    public UpdateDepartmentResponse createUpdateDepartmentResponse() {
        return new UpdateDepartmentResponse();
    }

    /**
     * Create an instance of {@link DeleteDepartmentRequest }
     * 
     */
    public DeleteDepartmentRequest createDeleteDepartmentRequest() {
        return new DeleteDepartmentRequest();
    }

    /**
     * Create an instance of {@link DeleteDepartmentResponse }
     * 
     */
    public DeleteDepartmentResponse createDeleteDepartmentResponse() {
        return new DeleteDepartmentResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeByIdRequest }
     * 
     */
    public GetEmployeeByIdRequest createGetEmployeeByIdRequest() {
        return new GetEmployeeByIdRequest();
    }

    /**
     * Create an instance of {@link GetEmployeeByIdResponse }
     * 
     */
    public GetEmployeeByIdResponse createGetEmployeeByIdResponse() {
        return new GetEmployeeByIdResponse();
    }

    /**
     * Create an instance of {@link EmployeeDtoResponse }
     * 
     */
    public EmployeeDtoResponse createEmployeeDtoResponse() {
        return new EmployeeDtoResponse();
    }

    /**
     * Create an instance of {@link GetAllEmployeesRequest }
     * 
     */
    public GetAllEmployeesRequest createGetAllEmployeesRequest() {
        return new GetAllEmployeesRequest();
    }

    /**
     * Create an instance of {@link GetAllEmployeesResponse }
     * 
     */
    public GetAllEmployeesResponse createGetAllEmployeesResponse() {
        return new GetAllEmployeesResponse();
    }

    /**
     * Create an instance of {@link AddEmployeeRequest }
     * 
     */
    public AddEmployeeRequest createAddEmployeeRequest() {
        return new AddEmployeeRequest();
    }

    /**
     * Create an instance of {@link AddEmployeeResponse }
     * 
     */
    public AddEmployeeResponse createAddEmployeeResponse() {
        return new AddEmployeeResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployeeRequest }
     * 
     */
    public UpdateEmployeeRequest createUpdateEmployeeRequest() {
        return new UpdateEmployeeRequest();
    }

    /**
     * Create an instance of {@link EmployeeResponse }
     * 
     */
    public EmployeeResponse createEmployeeResponse() {
        return new EmployeeResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployeeResponse }
     * 
     */
    public UpdateEmployeeResponse createUpdateEmployeeResponse() {
        return new UpdateEmployeeResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeeRequest }
     * 
     */
    public DeleteEmployeeRequest createDeleteEmployeeRequest() {
        return new DeleteEmployeeRequest();
    }

    /**
     * Create an instance of {@link DeleteEmployeeResponse }
     * 
     */
    public DeleteEmployeeResponse createDeleteEmployeeResponse() {
        return new DeleteEmployeeResponse();
    }

}
